{% set name = "OpenMiChroM" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: GIT_URL

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - OpenMiChroM

about:
  home: https://ndb.rice.edu/Open-MiChroM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SUMMARY

extra:
  recipe-maintainers:
    - USERNAME
